#!/usr/bin/env vpython3

def onefile(fname):
    data = open(fname, 'rt').read()
    data = data.replace('FPDF_EXPORT', 'extern')
    data = data.replace('FPDF_CALLCONV', '')
    open(fname, 'wt').write(data)

onefile('pdfium/include/fpdf_annot.h')
onefile('pdfium/include/fpdf_attachment.h')
onefile('pdfium/include/fpdf_catalog.h')
onefile('pdfium/include/fpdf_dataavail.h')
onefile('pdfium/include/fpdf_doc.h')
onefile('pdfium/include/fpdf_edit.h')
onefile('pdfium/include/fpdf_ext.h')
onefile('pdfium/include/fpdf_flatten.h')
onefile('pdfium/include/fpdf_formfill.h')
onefile('pdfium/include/fpdf_fwlevent.h')
onefile('pdfium/include/fpdf_javascript.h')
onefile('pdfium/include/fpdf_ppo.h')
onefile('pdfium/include/fpdf_progressive.h')
onefile('pdfium/include/fpdf_save.h')
onefile('pdfium/include/fpdf_searchex.h')
onefile('pdfium/include/fpdf_signature.h')
onefile('pdfium/include/fpdf_structtree.h')
onefile('pdfium/include/fpdf_sysfontinfo.h')
onefile('pdfium/include/fpdf_text.h')
onefile('pdfium/include/fpdf_thumbnail.h')
onefile('pdfium/include/fpdf_transformpage.h')
onefile('pdfium/include/fpdfview.h')
